# Programming Assignment 02 - NumPy Problems

**Name:** Sanika Mahind
**Roll Number:** MS2517

# Problem 1: Make a NumPy Array

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


# Explanation: np.array() converts a Python list into a NumPy array, which supports fast, vectorized numerical operations.

# Problem 2: Temperature Analysis

In [2]:
import numpy as np

def analyze_temperatures(temps):
    average = np.mean(temps)
    maximum = np.max(temps)
    minimum = np.min(temps)
    hottest_day = np.argmax(temps) + 1  # +1 so days start from 1, not 0
    above_average = temps[temps > average]
    return average, maximum, minimum, hottest_day, above_average

temperatures = np.array([32.5, 31.8, 30.2, 33.1, 34.5, 29.8, 31.0])
avg, max_temp, min_temp, hot_day, above_avg = analyze_temperatures(temperatures)

print("Average temperature:", avg)
print("Maximum temperature:", max_temp)
print("Minimum temperature:", min_temp)
print("Day with highest temperature: Day", hot_day)
print("Temperatures above average:", above_avg)

Average temperature: 31.842857142857145
Maximum temperature: 34.5
Minimum temperature: 29.8
Day with highest temperature: Day 5
Temperatures above average: [32.5 33.1 34.5]


# Explanation: np.mean, np.max, np.min give the basic stats directly. np.argmax returns the index of the highest value, so adding 1 converts it to a day number. Boolean indexing (temps > average) filters out only the days above average.

# Problem 3: Working with a Matrix

In [3]:
import numpy as np

matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

first_row = matrix[0]
last_row = matrix[-1]
first_col = matrix[:, 0]
last_col = matrix[:, -1]
middle_section = matrix[0:2, 1:3]
alternate_elements = matrix[::2, ::2]

print("First row:", first_row)
print("Last row:", last_row)
print("First column:", first_col)
print("Last column:", last_col)
print("Middle 2x2 section:\n", middle_section)
print("Every alternate element:\n", alternate_elements)
print("Shape:", matrix.shape)
print("Dimensions:", matrix.ndim)
print("Total elements:", matrix.size)

First row: [1 2 3 4]
Last row: [ 9 10 11 12]
First column: [1 5 9]
Last column: [ 4  8 12]
Middle 2x2 section:
 [[2 3]
 [6 7]]
Every alternate element:
 [[ 1  3]
 [ 9 11]]
Shape: (3, 4)
Dimensions: 2
Total elements: 12


# Explanation: Slicing with [:, 0] and [:, -1] picks a whole column, while [0]/[-1] picks a whole row. matrix[0:2, 1:3] slices out the overlapping middle rows and columns. matrix[::2, ::2] steps by 2 in both directions to pick alternate elements. .shape, .ndim, and .size are built-in array attributes.

# Problem 4: Even and Odd Numbers

In [4]:
import numpy as np

numbers = np.random.choice(np.arange(1, 51), size=15, replace=False)

even_numbers = numbers[numbers % 2 == 0]
odd_numbers = numbers[numbers % 2 != 0]

print("Original numbers:", numbers)
print("Even numbers:", even_numbers)
print("Odd numbers:", odd_numbers)

Original numbers: [45 46  8 29 47 38 14 24 31 26 42 43 12 37 30]
Even numbers: [46  8 38 14 24 26 42 12 30]
Odd numbers: [45 29 47 31 43 37]


# Explanation: np.random.choice randomly selects numbers from 1–50 without repeats. numbers % 2 == 0 creates a boolean mask that's True wherever the number is even, and that mask is used to filter the array directly — no manual loop needed.


# Problem 5: Numbers Above a Threshold

In [5]:
import numpy as np

data = np.random.randint(1, 101, size=30)

above_50 = data[data > 50]
between_25_75 = data[(data >= 25) & (data <= 75)]
count_above_50 = np.sum(data > 50)
avg_above_50 = np.mean(above_50)

print("Generated array:", data)
print("Values greater than 50:", above_50)
print("Values between 25 and 75:", between_25_75)
print("Count of values greater than 50:", count_above_50)
print("Average of values greater than 50:", avg_above_50)

Generated array: [36 23  7  8 69 75 52 48 10 28 15 40 67  7 68 56 88 22 16 21  8 60 66 57
 61 55 73 93 87 90]
Values greater than 50: [69 75 52 67 68 56 88 60 66 57 61 55 73 93 87 90]
Values between 25 and 75: [36 69 75 52 48 28 40 67 68 56 60 66 57 61 55 73]
Count of values greater than 50: 16
Average of values greater than 50: 69.8125


# Explanation: np.random.randint generates 30 random integers between 1 and 100. Boolean masks (data > 50, and a combined & condition for the range) filter the array. np.sum on a boolean array counts how many True values there are, since True is treated as 1

# Problem 6: Student Performance Matrix

In [6]:
import numpy as np

marks = np.array([
    [78, 82, 91],
    [65, 74, 80],
    [92, 88, 95],
    [56, 69, 72],
    [84, 90, 87]
])

student_avg = np.mean(marks, axis=1)
subject_avg = np.mean(marks, axis=0)
highest_mark = np.max(marks)
lowest_mark = np.min(marks)
top_student = np.argmax(student_avg) + 1
top_subject_index = np.argmax(subject_avg)
subjects = ["Mathematics", "Physics", "Programming"]

print("Average marks per student:", student_avg)
print("Average marks per subject:", subject_avg)
print("Highest mark overall:", highest_mark)
print("Lowest mark overall:", lowest_mark)
print("Student with highest average: Student", top_student)
print("Subject with highest average:", subjects[top_subject_index])

Average marks per student: [83.66666667 73.         91.66666667 65.66666667 87.        ]
Average marks per subject: [75.  80.6 85. ]
Highest mark overall: 95
Lowest mark overall: 56
Student with highest average: Student 3
Subject with highest average: Programming


# Explanation: axis=1 averages across each row (per student), while axis=0 averages down each column (per subject). np.argmax finds the index of the highest average, which is mapped back to a student number or subject name.

# Problem 7: Matrix Operations

In [7]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

addition = A + B
subtraction = A - B
elementwise_mult = A * B
matrix_mult = A @ B  # or np.dot(A, B)

print("Addition:\n", addition)
print("Subtraction:\n", subtraction)
print("Element-wise multiplication:\n", elementwise_mult)
print("Matrix multiplication:\n", matrix_mult)

Addition:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Subtraction:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
Element-wise multiplication:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]
Matrix multiplication:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


# Explanation: A * B multiplies corresponding elements independently (position-by-position), while A @ B performs true matrix multiplication — each result element is a sum of products across a row of A and a column of B. They differ because element-wise multiplication treats the arrays as grids of independent numbers, whereas matrix multiplication follows the mathematical definition involving dot products of rows and columns, which mixes values across the row/column rather than keeping them separate.

# Problem 8: Scientific Data Transformation

In [8]:
import numpy as np

def transform_data(data):
    squared = data ** 2
    sqrt_values = np.sqrt(data)
    exponential = np.exp(data)
    mean_transformed = np.mean(squared)
    return squared, sqrt_values, exponential, mean_transformed

measurements = np.array([2, 4, 6, 8, 10, 12])
squared, sqrt_vals, exp_vals, mean_val = transform_data(measurements)

print("Squares:", squared)
print("Square roots:", sqrt_vals)
print("Exponentials:", exp_vals)
print("Mean of squared data:", mean_val)

Squares: [  4  16  36  64 100 144]
Square roots: [1.41421356 2.         2.44948974 2.82842712 3.16227766 3.46410162]
Exponentials: [7.38905610e+00 5.45981500e+01 4.03428793e+02 2.98095799e+03
 2.20264658e+04 1.62754791e+05]
Mean of squared data: 60.666666666666664


# Explanation: NumPy applies ** 2, np.sqrt(), and np.exp() element-wise across the whole array in one operation, without needing a loop. The function returns all transformed arrays plus the mean of the squared values.

# Problem 9: Reshaping Experimental Data

In [9]:
import numpy as np

data = np.arange(1, 25)

reshaped_4x6 = data.reshape(4, 6)
reshaped_6x4 = data.reshape(6, 4)
reshaped_2x3x4 = data.reshape(2, 3, 4)

print("4x6 shape:", reshaped_4x6.shape)
print("6x4 shape:", reshaped_6x4.shape)
print("2x3x4 shape:", reshaped_2x3x4.shape)

flattened = reshaped_4x6.flatten()
print("Flattened back to 1D:", flattened)

4x6 shape: (4, 6)
6x4 shape: (6, 4)
2x3x4 shape: (2, 3, 4)
Flattened back to 1D: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


# Explanation: np.arange(1, 25) generates the numbers 1 to 24. reshape() rearranges the same 24 values into different dimensional layouts, as long as the total number of elements matches. flatten() converts any shape back into a single 1D array.

# Problem 10: Data Combination

In [10]:
import numpy as np

experiment_1 = np.array([10, 20, 30, 40, 50])
experiment_2 = np.array([15, 25, 35, 45, 55])

combined_1d = np.concatenate((experiment_1, experiment_2))
combined_rows = np.vstack((experiment_1, experiment_2))
combined_columns = np.column_stack((experiment_1, experiment_2))

print("Combined 1D array:", combined_1d, "shape:", combined_1d.shape)
print("Combined as rows:\n", combined_rows, "shape:", combined_rows.shape)
print("Combined as columns:\n", combined_columns, "shape:", combined_columns.shape)

Combined 1D array: [10 20 30 40 50 15 25 35 45 55] shape: (10,)
Combined as rows:
 [[10 20 30 40 50]
 [15 25 35 45 55]] shape: (2, 5)
Combined as columns:
 [[10 15]
 [20 25]
 [30 35]
 [40 45]
 [50 55]] shape: (5, 2)


# Explanation: np.concatenate joins the two arrays end-to-end into one long array. np.vstack stacks them as two separate rows in a matrix. np.column_stack places them side-by-side as two columns instead.

# Problem 11: Simple Data Cleaning

In [11]:
import numpy as np

measurements = np.array([10, 12, 15, 200, 13, 11, 14, 250, 12, 15])

invalid_mask = measurements > 100
invalid_values = measurements[invalid_mask]
valid_values = measurements[~invalid_mask]

mean_valid = np.mean(valid_values)
min_valid = np.min(valid_values)
max_valid = np.max(valid_values)

print("Original array:", measurements)
print("Invalid measurements:", invalid_values)
print("Valid measurements:", valid_values)
print("Mean of valid measurements:", mean_valid)
print("Minimum valid measurement:", min_valid)
print("Maximum valid measurement:", max_valid)

Original array: [ 10  12  15 200  13  11  14 250  12  15]
Invalid measurements: [200 250]
Valid measurements: [10 12 15 13 11 14 12 15]
Mean of valid measurements: 12.75
Minimum valid measurement: 10
Maximum valid measurement: 15


# Explanation: A boolean mask flags anything above 100 as invalid. ~invalid_mask (the ~ inverts the mask) selects everything that is not invalid. Since indexing with a mask returns a new array, the original measurements array is left untouched.

# Problem 12: Image-like Matrix

In [12]:
import numpy as np

image = np.array([
    [0, 0, 0, 255, 255],
    [0, 0, 128, 255, 255],
    [0, 128, 128, 128, 255],
    [0, 0, 128, 0, 0],
    [255, 0, 0, 0, 255]
])

min_intensity = np.min(image)
max_intensity = np.max(image)
mean_intensity = np.mean(image)
count_above_100 = np.sum(image > 100)
pixels_255 = image[image == 255]
bright_pixels = image[image > 100]

print("Minimum pixel intensity:", min_intensity)
print("Maximum pixel intensity:", max_intensity)
print("Mean pixel intensity:", mean_intensity)
print("Pixels with intensity > 100:", count_above_100)
print("Pixels equal to 255:", pixels_255)
print("New array of pixels > 100:", bright_pixels)

Minimum pixel intensity: 0
Maximum pixel intensity: 255
Mean pixel intensity: 97.0
Pixels with intensity > 100: 12
Pixels equal to 255: [255 255 255 255 255 255 255]
New array of pixels > 100: [255 255 128 255 255 128 128 128 255 128 255 255]


# Explanation: Since a 2D array is just numbers to NumPy, all the usual aggregate functions (min, max, mean) work directly on it, treating all rows and columns together. Boolean masks (image == 255, image > 100) extract the pixels satisfying those conditions into new 1D arrays.

# Problem 13: Experiment Comparison

In [13]:
import numpy as np

experiment_A = np.array([12, 15, 14, 18, 20, 17, 16])
experiment_B = np.array([10, 13, 15, 16, 19, 21, 18])

mean_A, mean_B = np.mean(experiment_A), np.mean(experiment_B)
std_A, std_B = np.std(experiment_A), np.std(experiment_B)
max_A, max_B = np.max(experiment_A), np.max(experiment_B)
min_A, min_B = np.min(experiment_A), np.min(experiment_B)
difference = experiment_A - experiment_B

print("Mean A:", mean_A, "| Mean B:", mean_B)
print("Std Dev A:", std_A, "| Std Dev B:", std_B)
print("Max A:", max_A, "| Max B:", max_B)
print("Min A:", min_A, "| Min B:", min_B)
print("Difference (A - B):", difference)

if std_A > std_B:
    print("Experiment A shows greater variation.")
else:
    print("Experiment B shows greater variation.")

Mean A: 16.0 | Mean B: 16.0
Std Dev A: 2.449489742783178 | Std Dev B: 3.4641016151377544
Max A: 20 | Max B: 21
Min A: 12 | Min B: 10
Difference (A - B): [ 2  2 -1  2  1 -4 -2]
Experiment B shows greater variation.


# Explanation: np.std() computes the standard deviation, a direct measure of how spread out the values are — the experiment with the higher standard deviation has more variation. Subtracting the two arrays directly gives an element-wise difference for each corresponding measurement.

# Problem 14: Mini Data Analysis Challenge

In [14]:
import numpy as np

def generate_data():
    return np.random.randint(1, 101, size=(10, 5))

def analyze_data(data):
    print("Dataset:\n", data)
    print("Shape:", data.shape)
    print("Dimensions:", data.ndim)

    variable_means = np.mean(data, axis=0)
    experiment_means = np.mean(data, axis=1)
    overall_max = np.max(data)
    overall_min = np.min(data)
    overall_mean = np.mean(data)
    above_mean = data[data > overall_mean]

    print("Mean of each variable:", variable_means)
    print("Mean of each experiment:", experiment_means)
    print("Maximum value:", overall_max)
    print("Minimum value:", overall_min)
    print("Values above overall mean:", above_mean)

    reshaped = data.reshape(5, 10)
    print("Reshaped (5x10):\n", reshaped)

    flattened = reshaped.flatten()
    print("Flattened back to 1D:", flattened)

dataset = generate_data()
analyze_data(dataset)

Dataset:
 [[ 43  16  18   7  54]
 [ 71  28  43  73  63]
 [ 83  83 100  22  83]
 [ 49  54  30  78  94]
 [ 77  87  55  70  51]
 [ 55  76  77  43  26]
 [ 37  68  62   3   5]
 [ 24  60  47  66  12]
 [ 69  68  95  64 100]
 [ 64  27  53  64  78]]
Shape: (10, 5)
Dimensions: 2
Mean of each variable: [57.2 56.7 58.  49.  56.6]
Mean of each experiment: [27.6 55.6 74.2 61.  68.  55.4 35.  41.8 79.2 57.2]
Maximum value: 100
Minimum value: 3
Values above overall mean: [ 71  73  63  83  83 100  83  78  94  77  87  70  76  77  68  62  60  66
  69  68  95  64 100  64  64  78]
Reshaped (5x10):
 [[ 43  16  18   7  54  71  28  43  73  63]
 [ 83  83 100  22  83  49  54  30  78  94]
 [ 77  87  55  70  51  55  76  77  43  26]
 [ 37  68  62   3   5  24  60  47  66  12]
 [ 69  68  95  64 100  64  27  53  64  78]]
Flattened back to 1D: [ 43  16  18   7  54  71  28  43  73  63  83  83 100  22  83  49  54  30
  78  94  77  87  55  70  51  55  76  77  43  26  37  68  62   3   5  24
  60  47  66  12  69  68  95  6

# Explanation: generate_data() builds a 10×5 array of random values. analyze_data() handles all the statistics: axis=0 gives per-variable (column) means and axis=1 gives per-experiment (row) means. A boolean mask against the overall mean pulls out above-average values. The array is then reshaped into a different valid 5×10 shape (same total elements) and flattened back to 1D — using two separate functions as required.

# Problem 15: Final Challenge — Student Performance Analysis

In [16]:
import numpy as np

def generate_marks(num_students=10, num_subjects=4):
    return np.random.randint(0, 101, size=(num_students, num_subjects))

def assign_grade(average):
    if average >= 90:
        return "A+"
    elif average >= 75:
        return "A"
    elif average >= 60:
        return "B"
    elif average >= 40:
        return "C"
    else:
        return "Fail"

def analyze_students(marks):
    student_avg = np.mean(marks, axis=1)
    subject_avg = np.mean(marks, axis=0)
    top_student = np.argmax(student_avg)
    bottom_student = np.argmin(student_avg)
    highest_mark = np.max(marks)
    lowest_mark = np.min(marks)
    above_75_count = np.sum(student_avg > 75)
    marks_above_90 = marks[marks > 90]

    records = []
    for i in range(len(marks)):
        grade = assign_grade(student_avg[i])
        records.append({
            "Student": f"Student {i+1}",
            "Marks": marks[i].tolist(),
            "Average": round(student_avg[i], 2),
            "Grade": grade
        })

    return {
        "records": records,
        "student_avg": student_avg,
        "subject_avg": subject_avg,
        "top_student": top_student,
        "bottom_student": bottom_student,
        "highest_mark": highest_mark,
        "lowest_mark": lowest_mark,
        "above_75_count": above_75_count,
        "marks_above_90": marks_above_90
    }

def display_report(marks, results):
    print("Marks Matrix:\n", marks)
    print("\n--- Student Performance Report ---")
    for record in results["records"]:
        print(f"{record['Student']}: Marks={record['Marks']}, "
              f"Average={record['Average']}, Grade={record['Grade']}")

    print("\nAverage marks per subject:", results["subject_avg"])
    print("Student with highest average:", results["records"][results["top_student"]]["Student"])
    print("Student with lowest average:", results["records"][results["bottom_student"]]["Student"])
    print("Highest mark in dataset:", results["highest_mark"])
    print("Lowest mark in dataset:", results["lowest_mark"])
    print("Students with average above 75:", results["above_75_count"])
    print("All marks greater than 90:", results["marks_above_90"])

marks = generate_marks()
results = analyze_students(marks)
display_report(marks, results)

Marks Matrix:
 [[35 75 43 63]
 [69 93 13 28]
 [94 21 64  3]
 [56 50 77 54]
 [79  0 64 93]
 [60 21 15 68]
 [47 84 53 57]
 [99 22 65 12]
 [33 97 24 42]
 [82 73 85 90]]

--- Student Performance Report ---
Student 1: Marks=[35, 75, 43, 63], Average=54.0, Grade=C
Student 2: Marks=[69, 93, 13, 28], Average=50.75, Grade=C
Student 3: Marks=[94, 21, 64, 3], Average=45.5, Grade=C
Student 4: Marks=[56, 50, 77, 54], Average=59.25, Grade=C
Student 5: Marks=[79, 0, 64, 93], Average=59.0, Grade=C
Student 6: Marks=[60, 21, 15, 68], Average=41.0, Grade=C
Student 7: Marks=[47, 84, 53, 57], Average=60.25, Grade=B
Student 8: Marks=[99, 22, 65, 12], Average=49.5, Grade=C
Student 9: Marks=[33, 97, 24, 42], Average=49.0, Grade=C
Student 10: Marks=[82, 73, 85, 90], Average=82.5, Grade=A

Average marks per subject: [65.4 53.6 50.3 51. ]
Student with highest average: Student 10
Student with lowest average: Student 6
Highest mark in dataset: 99
Lowest mark in dataset: 0
Students with average above 75: 1
All mark

# Explanation: generate_marks() creates a 10×4 array of random marks. assign_grade() maps an average to a letter grade using conditionals. analyze_students() does all the NumPy-based analysis (per-student and per-subject averages, extremes, counts, filtering) and packages each student's data — including their grade — into a list of dictionaries (records), which is a clean structure to store mixed data types (name, list of marks, average, grade) together. display_report() then prints everything in a readable format, keeping the analysis logic and the display logic in separate functions as the assignment asks.