## Problem 1 - Make a NumPy Array

In [1]:
import numpy as np

arr = np.array([10,20,30,40,50])

print(f"NumPy Array: {arr}")

NumPy Array: [10 20 30 40 50]


## Problem 2 - Temperature Analysis

In [3]:
import numpy as np

def temperature_analysis(temperatures):
    avg = np.mean(temperatures)
    maximum = np.max(temperatures)
    minimum = np.min(temperatures)
    highest_day = np.argmax(temperatures) + 1
    above_avg = temperatures[temperatures > avg]

    return avg , maximum , minimum , highest_day , above_avg

temperatures = np.array([32.5, 31.8, 30.2, 33.1, 34.5, 29.8, 31.0])

avg , maximum, minimum, highest_day , above_avg = \
temperature_analysis(temperatures)

print(f"Temperatures: {temperatures}")
print(f"Average temprature: {avg}")
print(f"Maximum temperature: {maximum}")
print(f"Minimum temperature: {minimum}")
print(f"Day with highest temperature: {highest_day}")
print(f"Tempratures above average: {above_avg}")


Temperatures: [32.5 31.8 30.2 33.1 34.5 29.8 31. ]
Average temprature: 31.842857142857145
Maximum temperature: 34.5
Minimum temperature: 29.8
Day with highest temperature: 5
Tempratures above average: [32.5 33.1 34.5]


## Problem 3 - Working with a Matrix

In [15]:
import numpy as np

matrix = np.array([[1, 2, 3, 4] , [5, 6, 7, 8] , [9, 10, 11, 12]])

print(f"Matrix:\n {matrix}")

print(f"\nFirst Row:\n {matrix[0]}")

print(f"\nLast Row:\n {matrix[-1]}")

print(f"\nFirst Column:\n {matrix[:, 0]}")

print(f"\nLast Column:\n {matrix[:, -1]}")

print(f"\nMiddle 2 x 2 section:\n {matrix[1:, 1:3]}")

print(f"\nEvery Alternate Element:\n {matrix.flatten()[::2]}")

print(f"\nShape: {matrix.shape}")

print(f"\nNumber of Dimensions: {matrix.ndim}")

print(f"\nTotal Elements: {matrix.size}")

Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

First Row:
 [1 2 3 4]

Last Row:
 [ 9 10 11 12]

First Column:
 [1 5 9]

Last Column:
 [ 4  8 12]

Middle 2 x 2 section:
 [[ 6  7]
 [10 11]]

Every Alternate Element:
 [ 1  3  5  7  9 11]

Shape: (3, 4)

Number of Dimensions: 2

Total Elements: 12


## Problem 4 - Even and Odd Numbers

In [2]:
import numpy as np

np.random.seed(42)

numbers = np.random.randint(1, 100, 20)

even = numbers[numbers % 2 == 0]
odd = numbers[numbers % 2 != 0]

print(f"Generated numbers: {numbers}")

print(f"\nEven numbers: {even}")

print(f"\nOdd numbers: {odd}")

Generated numbers: [52 93 15 72 61 21 83 87 75 75 88 24  3 22 53  2 88 30 38  2]

Even numbers: [52 72 88 24 22  2 88 30 38  2]

Odd numbers: [93 15 61 21 83 87 75 75  3 53]


## Problem 5 - Numbers Above a Threshold

In [6]:
import numpy as np

np.random.seed(10)

numbers = np.random.randint(1 , 101 , 10)

greater_than_50 = numbers[numbers > 50]
between_25_and_75 = numbers[(numbers >= 25) & (numbers <= 75)]

count = np.sum(numbers > 50)

average = np.mean(greater_than_50)

print(f"Generated Array:\n {numbers}")

print(f"\nValues greater than 50:\n {greater_than_50}")

print(f"\nValues between 25 and 75:\n {between_25_and_75}")

print(f"\nCount of values greater than 50: {count}")

print(f"\nAverage of values greater than 50: {average}")

Generated Array:
 [10 16 65 29 90 94 30  9 74  1]

Values greater than 50:
 [65 90 94 74]

Values between 25 and 75:
 [65 29 30 74]

Count of values greater than 50: 4

Average of values greater than 50: 80.75


## Problem 6 - Student Performance Matrix

In [9]:
import numpy as np

marks = np.random.randint(50 , 101 , size=(5, 3))

student_avg = np.mean(marks, axis=1)
subject_avg = np.mean(marks , axis=0)

highest_mark = np.max(marks)
lowest_mark = np.min(marks)

highest_student = np.argmax(student_avg) + 1
highest_subject = np.argmax(subject_avg)

subjects = ["Mathematics" , "Physics" , "Programming"]

print(f"Average marks of each student:\n {student_avg}")

print(f"\nAverage marks in each subject:\n {subject_avg}")

print(f"\nHighest mark: {highest_mark}")

print(f"\nLowest mark: {lowest_mark}")

print(f"\nStudent with highest average: {highest_student}")

print(f"\nSubject with highest average: {subjects[highest_subject]}")

Average marks of each student:
 [71.33333333 71.33333333 70.66666667 64.         65.66666667]

Average marks in each subject:
 [71.  65.  69.8]

Highest mark: 80

Lowest mark: 57

Student with highest average: 1

Subject with highest average: Mathematics


## Problem 7 - Matrix Operations

In [5]:
import numpy as np 

A = np.random.randint(1 , 10 , size=(3,3))

B = np.random.randint(1 , 10 , size=(3,3))

print(f"\nMatrix A:\n {A}")

print(f"\nMatrix B:\n {B}")

print(f"\nAddition:\n {A + B}")

print(f"\nSubtraction:\n {A - B}")

print(f"\nElement wise multiplication:\n {A * B}")

print(f"\nMatrix multiplication:\n {A @ B}")


Matrix A:
 [[6 4 7]
 [4 5 5]
 [7 6 1]]

Matrix B:
 [[4 3 6]
 [2 6 1]
 [3 4 3]]

Addition:
 [[10  7 13]
 [ 6 11  6]
 [10 10  4]]

Subtraction:
 [[ 2  1  1]
 [ 2 -1  4]
 [ 4  2 -2]]

Element wise multiplication:
 [[24 12 42]
 [ 8 30  5]
 [21 24  3]]

Matrix multiplication:
 [[53 70 61]
 [41 62 44]
 [43 61 51]]


## Problem 8 - Scientific Data Transformation

In [6]:
import numpy as np

def transform_data(data):
    square = data **2
    square_root = np.sqrt(data)
    exponential = np.exp(data)

    return square, square_root , exponential

data = np.array([2, 4, 6, 8, 10, 12])

square, square_root, exponential = transform_data(data)

print(f"Original data:\n {data}")

print(f"\nSquare:\n {square}")

print(f"\nSquare root:\n {square_root}")

print(f"\nExponential:\n {exponential}")

print(f"\nMean of square: {np.mean(square)}")

print(f"Mean of square root: {np.mean(square_root)}")

print(f"Mean of exponential: {np.mean(exponential)}")

Original data:
 [ 2  4  6  8 10 12]

Square:
 [  4  16  36  64 100 144]

Square root:
 [1.41421356 2.         2.44948974 2.82842712 3.16227766 3.46410162]

Exponential:
 [7.38905610e+00 5.45981500e+01 4.03428793e+02 2.98095799e+03
 2.20264658e+04 1.62754791e+05]

Mean of square: 60.666666666666664
Mean of square root: 2.5530849508680995
Mean of exponential: 31371.271866746192


## Problem 9 - Reshaping Experimental Data

In [12]:
import numpy as np

numbers = np.arange(1 ,25)

array_4x6 = numbers.reshape(4 , 6)
array_6x4 = numbers.reshape(6 , 4)
array_2x3x4 = numbers.reshape(2, 3, 4)

print(f"4 x 6 array:\n {array_4x6}")

print(f"\nShape: {array_6x4.shape}")

print(f"\n6 x 4 array:\n {array_6x4}")

print(f"\nShape: {array_6x4.shape}")

print(f"\n2 x 3 x 4 array:\n {array_2x3x4}")

print(f"\nShape: {array_2x3x4.shape}")

one_dimensional = array_4x6.reshape(-1)

print(f"\nBack to one-dimensional: {one_dimensional}")

4 x 6 array:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]

Shape: (6, 4)

6 x 4 array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

Shape: (6, 4)

2 x 3 x 4 array:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

Shape: (2, 3, 4)

Back to one-dimensional: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


## Problem 10 - Data Combination

In [1]:
import numpy as np

exp1 = np.array([10 , 20 , 30 , 40 , 50])
exp2 = np.array([15 , 25 , 35 , 45 , 55])

one_dim = np.concatenate((exp1 , exp2))

sep_rows = np.vstack((exp1 , exp2))

sep_cols = np.column_stack((exp1 , exp2))

print(f"One Dimensional Array:\n {one_dim}")
print(f"\nShape: {one_dim.shape}")

print(f"\nExperimantes as separate rows:\n {sep_rows}")
print(f"\nShape: {sep_rows.shape}")

print(f"\nExperimantes as separate columns:\n {sep_cols}")
print(f"\nShape: {sep_cols.shape}")


One Dimensional Array:
 [10 20 30 40 50 15 25 35 45 55]

Shape: (10,)

Experimantes as separate rows:
 [[10 20 30 40 50]
 [15 25 35 45 55]]

Shape: (2, 5)

Experimantes as separate columns:
 [[10 15]
 [20 25]
 [30 35]
 [40 45]
 [50 55]]

Shape: (5, 2)


## Problem 11 - Simple Data Cleaning

In [2]:
import numpy as np

data = np.array([10 , 12, 15 , 200 , 13 , 11 , 14 , 250 , 12 , 15])

invalid = data[data > 100]
valid = data[data <= 100]

print(f"Original data : {data}")

print(f"\nInvalid measurements: {invalid}")

print(f"\nValid measurements: {valid}")

print(f"\nMean of valid measurements: {np.mean(valid)}")

print(f"\nMinimum valid measurements: {np.min(valid)}")

print(f"\nMaximum valid measurements: {np.max(valid)}")

Original data : [ 10  12  15 200  13  11  14 250  12  15]

Invalid measurements: [200 250]

Valid measurements: [10 12 15 13 11 14 12 15]

Mean of valid measurements: 12.75

Minimum valid measurements: 10

Maximum valid measurements: 15


## Problem 12 - Image like Matrix

In [7]:
import numpy as np 

img = np.array([[0 , 0 , 0 , 255 , 255] , [0 , 0 , 128 , 255 , 255] , [0 , 128 , 128 , 128 , 255] , [0 , 0 , 128 , 0 , 0] , [255 , 0 , 0 , 0 , 255]])

high_pixels = img[img > 100]
pixels_255 = img[img == 255]

print(f"Image :\n {img}")

print(f"\nMinimum pixel intensity: {np.min(img)}")

print(f"\nMaximum pixel intensity : {np.max(img)}")

print(f"\nMean pixel intensity : {np.mean(img)}")

print(f"\nNumbers of pixels greater than 100 : {np.sum(img > 100)}")

print(f"\nPixels equal to 255 : {pixels_255}")

print(f"\nPixels greater than 100 : {high_pixels}")

Image :
 [[  0   0   0 255 255]
 [  0   0 128 255 255]
 [  0 128 128 128 255]
 [  0   0 128   0   0]
 [255   0   0   0 255]]

Minimum pixel intensity: 0

Maximum pixel intensity : 255

Mean pixel intensity : 97.0

Numbers of pixels greater than 100 : 12

Pixels equal to 255 : [255 255 255 255 255 255 255]

Pixels greater than 100 : [255 255 128 255 255 128 128 128 255 128 255 255]


## Problem 13 - Experiment Comaprison

In [10]:
import numpy as np 

exp_A = np.random.randint(10 , 20 , 7)

exp_B = np.random.randint(10 , 20 , 7)

print(f"Experiment A : {exp_A}")
print(f"\nExperiment B : {exp_B}")

print(f"\nMean of Experiment A : {np.mean(exp_A)}")
print(f"\nMean of Experiment B : {np.mean(exp_B)}")

print(f"\nStandard Deviation of Experment A : {np.std(exp_A)}")
print(f"\nStandard Deviation of experiment B : {np.std(exp_B)}")

print(f"\nMaximum of Experment A : {np.max(exp_A)}")
print(f"\nMaximum of Experment B : {np.max(exp_B)}")

print(f"\nMinimum of Experment A : {np.max(exp_A)}")
print(f"\nMinimum of Experment B : {np.max(exp_B)}")

print(f"\nDifference between  Experment A & Experiment B : {exp_A - exp_B}")

if np.std(exp_A) > np.std(exp_B):
    print("\nExperiment A  shows greater variation.")
else:
    print("\nExperiment B  shows greater variation.")


Experiment A : [14 17 11 16 13 10 19]

Experiment B : [11 19 12 19 18 11 14]

Mean of Experiment A : 14.285714285714286

Mean of Experiment B : 14.857142857142858

Standard Deviation of Experment A : 3.0101867865293537

Standard Deviation of experiment B : 3.440455593940656

Maximum of Experment A : 19

Maximum of Experment B : 19

Minimum of Experment A : 19

Minimum of Experment B : 19

Difference between  Experment A & Experiment B : [ 3 -2 -1 -3 -5 -1  5]

Experiment B  shows greater variation.


## Problem 14 - Mini Data Analysis Challenge

In [17]:
import numpy as np

def generate_data() :
    np.random.seed(1)
    return np.random.randint(1 , 101 , (10 , 5))

def analyze_data(data):
    print(f"\nDataset :\n {data}")

    print(f"\nShape : {data.shape}")
    print(f"\nDimensions : {data.ndim}")

    print(f"\nMean of each variable :\n {np.mean(data , axis=0)}")
    print(f"\nMean of each experiment :\n {np.mean(data , axis=1)}")

    print(f"\nMaximum value : {np.max(data)}")
    print(f"\nMinimum value : {np.min(data)}")

    print(f"Overall Mean : {np.mean(data)}")

    print(f"\nValues above overall mean : {data[data > np.mean(data)]}")

    print(f"\nReshaped data :\n {data.reshape(5 , 10)}")

    

    print(f"\nFlattened data :\n {(data.reshape(5, 10).flatten())}")

data = generate_data()
analyze_data(data)


Dataset :
 [[38 13 73 10 76]
 [ 6 80 65 17  2]
 [77 72  7 26 51]
 [21 19 85 12 29]
 [30 15 51 69 88]
 [88 95 97 87 14]
 [10  8 64 62 23]
 [58  2  1 61 82]
 [ 9 89 14 48 73]
 [31 72  4 71 22]]

Shape : (10, 5)

Dimensions : 2

Mean of each variable :
 [36.8 46.5 46.1 46.3 46. ]

Mean of each experiment :
 [42.  34.  46.6 33.2 50.6 76.2 33.4 40.8 46.6 40. ]

Maximum value : 97

Minimum value : 1
Overall Mean : 44.34

Values above overall mean : [73 76 80 65 77 72 51 85 51 69 88 88 95 97 87 64 62 58 61 82 89 48 73 72
 71]

Reshaped data :
 [[38 13 73 10 76  6 80 65 17  2]
 [77 72  7 26 51 21 19 85 12 29]
 [30 15 51 69 88 88 95 97 87 14]
 [10  8 64 62 23 58  2  1 61 82]
 [ 9 89 14 48 73 31 72  4 71 22]]

Flattened data :
 [38 13 73 10 76  6 80 65 17  2 77 72  7 26 51 21 19 85 12 29 30 15 51 69
 88 88 95 97 87 14 10  8 64 62 23 58  2  1 61 82  9 89 14 48 73 31 72  4
 71 22]


## Problem 15 - Final Student Performance Analysis

In [19]:
import numpy as np

def generate_marks() :
    np.random.seed(7)
    return np.random.randint(0 ,101 , (10 , 4))

def calculate_grade(average):
    if average >= 90 :
        return "A+"
    elif average >= 80 :
        return "A"
    elif average >= 70 :
        return "B"
    elif average >= 60 :
        return "C"
    elif average >= 50 :
        return "D"
    else :
        return "F"

def analyze_stu(marks):
    stu_average = np.mean(marks, axis=1)
    sub_average = np.mean(marks , axis=0)

    highest_stu = np.argmax(stu_average) + 1
    lowest_stu = np.argmin(stu_average) + 1

    higest_marks = np.max(marks)
    lowest_marks = np.min(marks)

    stu_above_75 = np.sum(stu_average > 75)

    marks_above_90 = marks[marks > 90]

    grades = []

    for average in stu_average:
        grades.append(calculate_grade(average))

    stu_info = []

    for i in range(10):
        stu_info.append({
            "Student" : i + 1,
            "Average" : stu_average[i],
            "Grade" : grades[i]
        })

    print(f"\nStudents marks :\n {marks}")

    print(f"\nAverage mark of every student :\n {stu_average}")

    print(f"\nAverage mark of every subject :\n {sub_average}")

    print(f"\nStudent with highest average : {highest_stu}")

    print(f"\nStudent with lowest average : {lowest_stu}")

    print(f"\nHighest marks : {higest_marks}")

    print(f"\nLowest marks : {lowest_marks}")

    print(f"\nStudents with average above 75 :\n {stu_above_75}")

    print(f"\nMarks greater than 90 :\n {marks_above_90}")

    print("\nFinal Student Information : ")

    for stu in stu_info:
        print(stu)

marks = generate_marks()
analyze_stu(marks)


Students marks :
 [[47 68 25 67]
 [83 23 92 57]
 [14 23 72 89]
 [42 90  8 39]
 [68 48  7 44]
 [ 0 75 55  6]
 [19 60 44 63]
 [69 56 24 55]
 [53 61 64 34]
 [56 73 78 38]]

Average mark of every student :
 [51.75 63.75 49.5  44.75 41.75 34.   46.5  51.   53.   61.25]

Average mark of every subject :
 [45.1 57.7 46.9 49.2]

Student with highest average : 2

Student with lowest average : 6

Highest marks : 92

Lowest marks : 0

Students with average above 75 :
 0

Marks greater than 90 :
 [92]

Final Student Information : 
{'Student': 1, 'Average': 51.75, 'Grade': 'D'}
{'Student': 2, 'Average': 63.75, 'Grade': 'C'}
{'Student': 3, 'Average': 49.5, 'Grade': 'F'}
{'Student': 4, 'Average': 44.75, 'Grade': 'F'}
{'Student': 5, 'Average': 41.75, 'Grade': 'F'}
{'Student': 6, 'Average': 34.0, 'Grade': 'F'}
{'Student': 7, 'Average': 46.5, 'Grade': 'F'}
{'Student': 8, 'Average': 51.0, 'Grade': 'D'}
{'Student': 9, 'Average': 53.0, 'Grade': 'D'}
{'Student': 10, 'Average': 61.25, 'Grade': 'C'}
